databases:
  - name: code-ninja0208-portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio

services:
  - type: web
    name: code-ninja0208-portfolio
    runtime: node
    plan: free
    branch: main
    buildCommand: yarn install --no-frozen-lockfile && yarn prisma migrate deploy && yarn build
    startCommand: yarn start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: code-ninja0208-portfolio-db
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: code-ninja0208-portfolio-db
          property: connectionString
      - key: SITE_URL
        value: https://code-ninja0208-portfolio.onrender.com/
