import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Junior Developer',
    company: 'CASERS',
    company_legal_name: 'CASERS',
    logo: '/images/careers/casers.png',
    location: "Ukraine 🇺🇦",
    location_type: 'Remote',
    type: 'Part-time',
    start_date: '2017-10',
    end_date: '2018-12',
    industry: 'education',
    link: 'https://casers.org/',
    responsibilities: [
      'Developed the building company website using React & Bootstrap.',
      'Built Education system for the Universities and added the Certification Feature.',
      'Closely collaborated with backend engineers and product team members to build fully responsive platform.',
      "Increased University and Companies's registration count by 20% with adding new Competition feature.",
      'Provided the Guidance for the educational purpose and guide the users about how to use the education platform.',
    ],
  },
  {
    position: 'Full Stack DEVELOPER',
    company: 'Valtech',
    company_legal_name: 'Valtech Corporation',
    logo: '/images/careers/valtron.png',
    location: 'N/A',
    location_type: 'Remote',
    type: 'Part-time',
    start_date: '2018-12',
    end_date: '2021-10',
    industry: 'Industry',
    link: 'https://valtechcorp.com/',
    responsibilities: [
      'Developed a front-end using React.',
      'Integrated ML based microservices using Redux and Redux Toolkit.',
      'Integrated CMS system using Netlify.',
      'Expertly deployed solutions on both Binance Smart Chain (BSC) and Ethereum networks.',
      'Engineered popular backend systems with NodeJS, Express.js.',
      'Enhanced the website performance by implementing CDN.',
    ],
  },
  {
    position: 'Full Stack Web3 Developer',
    company: 'LAZY LIONS',
    company_legal_name: 'LAZY LIONS',
    logo: '/images/careers/lazylion.png',
    location: 'Australia 🇦🇺',
    location_type: 'Remote',
    type: 'Part-time',
    start_date: '2022-07',
    end_date: '2023-04',
    industry: 'NFT',
    link: 'https://opensea.io/collection/lazy-lions',
    responsibilities: [
      "Developed Lazy Cubs' frontend with Next.js, TypeScript, Ether.js, useDapp",
      'Engineered Node.js/GraphQL backend, enhancing web3 integration & response speed.',
      "Optimized smart contract interaction, cutting response time by 0.5s via Subgraph",
      "Conducted rigorous smart contract testing on Rinkeby Testnet for robust deployment .",
    ],
  },
  {
    position: 'Senior Full Stack Engineer',
    company: 'Fashinza',
    company_legal_name: 'Fashinza',
    logo: '/images/careers/fashinza.png',
    location: 'U.S.',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2023-07',
    end_date: null,
    industry: 'B2B',
    link: 'https://fashinza.com/en-us/',
    responsibilities: [
      'Engaged actively with the developer community to stay at the forefront of industry trends and best practices about AI, ML.',
      'Successfully completed high-value projects of one U.S. client in Upwork, generating earnings of $7,000 through exceptional technical skills and client satisfaction.',
      "Currently expanding technical proficiency by studying Rust and Go, aiming to enhance capabilities in blockchain development.",
    ],
  },
];
