import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Web Developer',
    company: 'Valtron',
    company_legal_name: 'Valtech Corporation',
    logo: '/images/careers/valtron.png',
    location: "L' viv  Ukraine 🇺🇦",
    location_type: 'Remote',
    type: 'Part-time',
    start_date: '2017-05',
    end_date: '2018-11',
    industry: 'Industry',
    link: 'https://valtechcorp.com/',
    responsibilities: [
      'Developed a front-end with a modular dashboard interface using React, TypeScript, and Jest.',
      'Created a custom component library with Restyle, and Storybook, saving development time and common utility functions.',
      'Integrated ML based microservices using Redux and Redux Toolkit.',
      'Used React Native animated API to build light animations for better User Experience.',
      'Wrote a CI/CD pipeline for mobile app release process using GitHub actions.',
    ],
  },
  {
    position: 'BLOCKCHAIN DEVELOPER',
    company: 'CHEECOIN',
    company_legal_name: 'CHEECOIN',
    logo: '/images/careers/cheecoin.png',
    location: 'N/A',
    location_type: 'Remote',
    type: 'Part-time',
    start_date: '2019-01',
    end_date: '2020-01',
    industry: 'NFT',
    link: 'https://coinmarketcap.com/currencies/cheecoin/',
    responsibilities: [
      'Spearheaded the development of an NFT platform leveraging ERC-721 to aid animal rescue initiatives.',
      'Successfully led a team in crafting and deploying smart contract code, passing a comprehensive audit by SlowMist.',
      'Engineered core features including an NFT marketplace, audit processes, and proxy deployment.',
      'Expertly deployed solutions on both Binance Smart Chain (BSC) and Ethereum networks.',
      'Drove significant NFT sales through strategic development and governance.',
      'Demonstrated mastery in Solidity, Truffle suite, smart contract auditing, and proxy contract implementation.',
    ],
  },
  {
    position: 'Full Stack Developer',
    company: 'Bloomberg',
    company_legal_name: 'A Scientific Business Solutions LLC',
    logo: '/images/careers/bloomberg.png',
    location: 'California, U.S. 🇺🇸',
    location_type: 'Remote',
    type: 'Part-time',
    start_date: '2020-02',
    end_date: '2022-01',
    industry: 'IT',
    link: 'https://www.bloomberg.com/profile/company/1699565D:US',
    responsibilities: [
      'Spearheaded full-stack development at DedicatedDevelopers, A Scientific Business Solutions LLC in San Francisco, harnessing state-of-the-art technologies to craft superior web and mobile applications.',
      'Managed and executed over 20 multifaceted projects for 12 international clients, encompassing e-commerce, social networking, healthcare, and enterprise solutions.',
      'Fostered teamwork and innovation, employing industry-leading platforms and tools to surpass project objectives with a client-focused mindset.',
      'Demonstrated frontend expertise with ReactJS, VueJS, Angular, and leveraged Next.js, Gatsby, Vuetify, and VuePress for optimized UI performance and SEO.',
      'Specialized in mobile app development using React Native and Expo for enhanced compatibility and user experience.',
      'Engineered robust backend systems with Laravel, CodeIgniter, NodeJS, Express.js, NestJS, Django, .Net and GraphQL, alongside CMS development with WordPress, Shopify, and Drupal.',
      'Achieved a 98% client satisfaction rate by consistently delivering projects that excel in functionality, design, and performance, driving business growth and digital transformation.',
    ],
  },
  {
    position: 'Full Stack Web3 Engineer',
    company: 'LAZY LIONS',
    company_legal_name: 'LAZY LIONS',
    logo: '/images/careers/lazylion.png',
    location: 'Australia 🇦🇺',
    location_type: 'Remote',
    type: 'Part-time',
    start_date: '2022-02',
    end_date: '2022-12',
    industry: 'NFT',
    link: 'https://opensea.io/collection/lazy-lions',
    responsibilities: [
      "Developed Lazy Cubs' frontend with Next.js, TypeScript, Ether.js, useDapp",
      'Engineered Node.js/GraphQL backend, enhancing web3 integration & response speed.',
      "Optimized smart contract interaction, cutting response time by 0.5s via Subgraph",
      "Conducted rigorous smart contract testing on Rinkeby Testnet for robust deployment .",
    ],
  },
  {
    position: 'Full Stack Blockchain Engineer',
    company: 'SELF EMPLOYED',
    company_legal_name: 'SELF EMPLOYED',
    logo: '/images/careers/upwork.png',
    location: 'Ukraine 🇺🇦',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2023-07',
    end_date: null,
    industry: 'IT',
    link: 'https://upwork.com/',
    responsibilities: [
      'Engaged actively with the developer community to stay at the forefront of industry trends and best practices about AI, ML.',
      'Successfully completed high-value projects of one U.S. client in Upwork, generating earnings of $7,000 through exceptional technical skills and client satisfaction.',
      "Currently expanding technical proficiency by studying Rust and Go, aiming to enhance capabilities in blockchain development.",
    ],
  },
];
